### ISSUE TITLE
Integrate MySensors with Thingsboard

### ISSUE THREAD

**Issue by chamroeunbm** [theolind/pymysensors#344] opened 2021-04-17 03:14 UTC
I have deployed Thingsboard(Community Edition) and try with a few self-built sensors. I find Thingsboard is very mature and feature rich and very user friendly. The down side is it doesn't have Sensor level code support or due to my limited knowledge of it. For this, i thing Mysensors complement it. So my thought is to integrate them.

MQTT payload of thingsboard is very simple and diffferent from MySensors MQTT payload. (https://thingsboard.io/docs/iot-gateway/config/mqtt/)
So i think maybe i need to customize the Mysensors gateway code or your library can help.

Thanks for your suggestion. Please note that I am new to both of this so maybe someone has a better solution.

**Comment by MartinHjelmare** [comment] 2021-04-17 09:36
The pymysensors library would require you to run the Python code somehow. I'm not familiar with Thingsboard and it's capabilities.

If you're not already locked into Thingsboard I'd recommend Home Assistant. It has more than 1000 integrations and mysensors is one of them. You can integrate directly with MQTT if you'd prefer that too.

https://www.home-assistant.io/

**Comment by MartinHjelmare** [comment] 2021-04-17 09:37
I'll close the issue since it's not a bug.

**Closed by MartinHjelmare** 2021-04-17 09:37 UTC
